name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository and fetch the main branch
      - name: Checkout Code
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git fetch --depth=1 origin refs/heads/main
          git checkout ${{ github.sha }}

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker image
      - name: Build Docker Image
        run: |
          cd repo
          docker build -t ghcr.io/${{ github.repository }}/reg-doc:latest .

      # Push Docker image to GitHub Container Registry
      - name: Push Docker Image
        run: |
          cd repo
          docker push ghcr.io/${{ github.repository }}/reg-doc:latest
