name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up SSH authentication
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Step 2: Clone the repository
      - name: Checkout Code
        run: |
          git clone git@github.com:${{ github.repository }} repo
          cd repo
          git fetch --depth=1 origin refs/heads/main
          git checkout ${{ github.sha }}

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: |
          cd repo
          docker build -t ghcr.io/${{ github.repository }}/reg-doc:latest .

      # Step 5: Push Docker image to GitHub Container Registry
      - name: Push Docker Image
        run: |
          cd repo
          docker push ghcr.io/${{ github.repository }}/reg-doc:latest
