name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        run: |
          git clone ${{ github.repository_url }} .
          git fetch --depth=1 origin ${{ github.ref }}
          git checkout ${{ github.sha }}

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/docuseal:latest .

      # Push Docker image to GitHub Container Registry
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/docuseal:latest

